version: 1
sequences:
- protein:
    id: A
    sequence: RNFNDSNPFMPYRDRPQRHKQCQTTIHTPTPGDYERWSNWHCRLAIFVTMWFPHAHCQPRSCEPYETAQFSSYINMAVVKDTTQPSRITMWGLAGYAHSGRAMHGVVNHRDLHPQPMSFKPSRGVEIFHHTTQVGRYKLYAQFHYFMEPNCGWGPEWMEEWHAPCLLPVSHSQRGCGSRVKYQKAAVRGRLVMTVTKTMQHHTAPDRDCQDFCSGRMPERYNPRPSDLCADHCYWYYTWK
    msa: empty
- protein:
    id: B
    sequence: LEEKKVCQGTSNKLTQLGTFEDHFLSLQRMFNNCEVVLGNLEITYVQRNYDLSFLKTIQEVAGYVLIALNTVERIPLENLQIIRGNMYYENSYALAVLSNYDANKTGLKELPMRNLQEILHGAVRFSNNPALCNVESIQWRDIVSSDFLSNMSMDFQNHLGSCQKCDPSCPNGSCWGAGEENCQKLTKIICAQQCSGRCRGKSPSDCCHNQCAAGCTGPRESDCLVCRKFRDEATCKDTCPPLMLYNPTTYQMDVNPEGKYSFGATCVKKCPRNYVVTDHGSCVRACGADSYEMEEDGVRKCKKCEGPCRKVCNGIGIGEFKDSLSINATNIKHFKNCTSISGDLHILPVAFRGDSFTHTPPLDPQELDILKTVKEITGFLLIQAWPENRTDLHAFENLEIIRGRTKQHGQFSLAVVSLNITSLGLRSLKEISDGDVIISGNKNLCYANTINWKKLFGTSGQKTKIISNRGENSCKATGQVCHALCSPEGCWGPEPRDCVSCRNVSRGRECVDKCNLLEGEPREFVENSECIQCHPECLPQAMNITCTGRGPDNCIQCAHYIDGPHCVKTCPAGVMGENNTLVWKYADAGHVCHLCHPNCTYGCTGPGLEGCPTNGPKIPSIATGMVGALLLLLVVALGIGLFM
    msa: empty
